name: quantum-algorithms-lab
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - notebook
  - ipykernel
  - numpy
  - sympy
  - matplotlib
  - pylatexenc
  - pip:
      - qiskit
      - qiskit-aer
      - cirq
      - pennylane
